package com.nailbitebreaker.data

import android.content.Context
import androidx.room.Database
import androidx.room.Room
import androidx.room.RoomDatabase

/**
 * Room database singleton for the NailBiteBreaker app.
 *
 * Schema: version 1, single entity [UrgEvent].
 * exportSchema is false for simplicity; set it to true and provide a
 * schema export directory in production to support automated schema migrations.
 *
 * Thread safety is ensured by double-checked locking on [getInstance].
 */
@Database(entities = [UrgEvent::class], version = 1, exportSchema = false)
abstract class HabitDatabase : RoomDatabase() {

    /** Provides access to the [UrgEventDao] implementation generated by Room. */
    abstract fun urgEventDao(): UrgEventDao

    companion object {

        @Volatile
        private var INSTANCE: HabitDatabase? = null

        /**
         * Returns the singleton [HabitDatabase] instance, creating it only once.
         *
         * The @Volatile annotation on [INSTANCE] ensures that writes are visible
         * to all threads immediately, and the synchronized block prevents two
         * threads from creating the database concurrently.
         *
         * @param context Used to locate the database file on disk — always pass
         *                the Application context to avoid memory leaks.
         */
        fun getInstance(context: Context): HabitDatabase =
            INSTANCE ?: synchronized(this) {
                INSTANCE ?: Room.databaseBuilder(
                    context.applicationContext,
                    HabitDatabase::class.java,
                    "nail_bite_breaker.db"
                ).build().also { INSTANCE = it }
            }
    }
}
